apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-admin
  namespace: sso          # ⬅️ ใช้ sso สำหรับ service ตระกูล sso-admin
rules:
  - apiGroups:
      - ""                # core API group (pods/services/configmaps/secrets)
      - apps              # deployments
    resources:
      - pods
      - deployments
      - services
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin-binding
  namespace: sso
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-admin       # ต้องตรงกับ Role ด้านบน
subjects:
  - kind: User                # หรือ ServiceAccount / Group ก็ได้
    name: some-user@example.com
    apiGroup: rbac.authorization.k8s.io
