# sender-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sender-svc
  namespace: internal-api-demo
spec:
  type: NodePort              # หรือ LoadBalancer/ใช้ Ingress ก็ได้
  selector:
    app: sender-web
  ports:
  - port: 80                  # Service port ฝั่ง client
    targetPort: 3000          # containerPort ของ sender-web
    nodePort: 30080           # (กรณี NodePort)
